# Generated by Django 5.2.3 on 2025-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_remove_shipment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
