# Generated by Django 5.2.3 on 2025-07-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='notes',
        ),
    ]
