# Generated by Django 5.2.3 on 2025-07-03 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_shipment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
