# Generated by Django 5.2.3 on 2025-07-03 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipmentitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
