# Generated by Django 5.2.3 on 2025-07-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
        ('shipments', '0006_alter_shipmentitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
