# Generated by Django 5.2.3 on 2025-07-10 20:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='profile_images/default.png', force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='profile_images/'),
        ),
    ]
