# Generated by Django 5.2.3 on 2025-07-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
        ('shipments', '0008_factory_alter_shipment_factory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Supermarket',
        ),
    ]
