<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-10 19:52
=======
# Generated by Django 5.2.3 on 2025-07-10 20:20
>>>>>>> 6da028dde9fcd88b65b84af8ae4fc831eeb8de2a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
